var namespacebolt_1_1mgt =
[
    [ "device", "namespacebolt_1_1mgt_1_1device.html", "namespacebolt_1_1mgt_1_1device" ],
    [ "ActiveProblem", "structbolt_1_1mgt_1_1_active_problem.html", "structbolt_1_1mgt_1_1_active_problem" ],
    [ "ActiveTask", "structbolt_1_1mgt_1_1_active_task.html", "structbolt_1_1mgt_1_1_active_task" ],
    [ "AllocationError", "structbolt_1_1mgt_1_1_allocation_error.html", null ],
    [ "BaseProblem", "classbolt_1_1mgt_1_1_base_problem.html", "classbolt_1_1mgt_1_1_base_problem" ],
    [ "BaseTask", "classbolt_1_1mgt_1_1_base_task.html", "classbolt_1_1mgt_1_1_base_task" ],
    [ "BufferAllocationWrapper", "classbolt_1_1mgt_1_1_buffer_allocation_wrapper.html", "classbolt_1_1mgt_1_1_buffer_allocation_wrapper" ],
    [ "DeviceImagePointer", "classbolt_1_1mgt_1_1_device_image_pointer.html", "classbolt_1_1mgt_1_1_device_image_pointer" ],
    [ "ExecutionError", "structbolt_1_1mgt_1_1_execution_error.html", null ],
    [ "FftCalculatorPointer", "classbolt_1_1mgt_1_1_fft_calculator_pointer.html", "classbolt_1_1mgt_1_1_fft_calculator_pointer" ],
    [ "GetSmartPointerHelper", "structbolt_1_1mgt_1_1_get_smart_pointer_helper.html", null ],
    [ "GetSmartPointerHelper< DeviceImage< TElement, tDimension > >", "structbolt_1_1mgt_1_1_get_smart_pointer_helper_3_01_device_image_3_01_t_element_00_01t_dimension_01_4_01_4.html", "structbolt_1_1mgt_1_1_get_smart_pointer_helper_3_01_device_image_3_01_t_element_00_01t_dimension_01_4_01_4" ],
    [ "GetSmartPointerHelper< FftCalculator< tDim, TPolicy > >", "structbolt_1_1mgt_1_1_get_smart_pointer_helper_3_01_fft_calculator_3_01t_dim_00_01_t_policy_01_4_01_4.html", "structbolt_1_1mgt_1_1_get_smart_pointer_helper_3_01_fft_calculator_3_01t_dim_00_01_t_policy_01_4_01_4" ],
    [ "GetSmartPointerHelper< TextureImage< TElement, tDimension, TCudaType > >", "structbolt_1_1mgt_1_1_get_smart_pointer_helper_3_01_texture_image_3_01_t_element_00_01t_dimension_00_01_t_cuda_type_01_4_01_4.html", "structbolt_1_1mgt_1_1_get_smart_pointer_helper_3_01_texture_image_3_01_t_element_00_01t_dimension_00_01_t_cuda_type_01_4_01_4" ],
    [ "GpuBufferView", "classbolt_1_1mgt_1_1_gpu_buffer_view.html", "classbolt_1_1mgt_1_1_gpu_buffer_view" ],
    [ "GpuMemoryManager", "classbolt_1_1mgt_1_1_gpu_memory_manager.html", "classbolt_1_1mgt_1_1_gpu_memory_manager" ],
    [ "GpuWorker", "classbolt_1_1mgt_1_1_gpu_worker.html", "classbolt_1_1mgt_1_1_gpu_worker" ],
    [ "GpuWorkerConfiguration", "classbolt_1_1mgt_1_1_gpu_worker_configuration.html", "classbolt_1_1mgt_1_1_gpu_worker_configuration" ],
    [ "HashMapMemoryCache", "classbolt_1_1mgt_1_1_hash_map_memory_cache.html", "classbolt_1_1mgt_1_1_hash_map_memory_cache" ],
    [ "ImageDescriptor", "classbolt_1_1mgt_1_1_image_descriptor.html", "classbolt_1_1mgt_1_1_image_descriptor" ],
    [ "ImageDescriptor< FftCalculator< tDim, TPolicy > >", "classbolt_1_1mgt_1_1_image_descriptor_3_01_fft_calculator_3_01t_dim_00_01_t_policy_01_4_01_4.html", "classbolt_1_1mgt_1_1_image_descriptor_3_01_fft_calculator_3_01t_dim_00_01_t_policy_01_4_01_4" ],
    [ "IProblem", "classbolt_1_1mgt_1_1_i_problem.html", "classbolt_1_1mgt_1_1_i_problem" ],
    [ "ITask", "classbolt_1_1mgt_1_1_i_task.html", "classbolt_1_1mgt_1_1_i_task" ],
    [ "LRUMemoryCache", "classbolt_1_1mgt_1_1_l_r_u_memory_cache.html", "classbolt_1_1mgt_1_1_l_r_u_memory_cache" ],
    [ "MgtError", "structbolt_1_1mgt_1_1_mgt_error.html", null ],
    [ "MultithreadLaunchError", "structbolt_1_1mgt_1_1_multithread_launch_error.html", null ],
    [ "OutOfMemory", "structbolt_1_1mgt_1_1_out_of_memory.html", null ],
    [ "ResourceConstraints", "classbolt_1_1mgt_1_1_resource_constraints.html", "classbolt_1_1mgt_1_1_resource_constraints" ],
    [ "Scheduler", "classbolt_1_1mgt_1_1_scheduler.html", "classbolt_1_1mgt_1_1_scheduler" ],
    [ "SchedulerConfiguration", "classbolt_1_1mgt_1_1_scheduler_configuration.html", "classbolt_1_1mgt_1_1_scheduler_configuration" ],
    [ "SharedCacheBadTypeError", "structbolt_1_1mgt_1_1_shared_cache_bad_type_error.html", null ],
    [ "SharedMemoryCache", "classbolt_1_1mgt_1_1_shared_memory_cache.html", "classbolt_1_1mgt_1_1_shared_memory_cache" ],
    [ "TaskTooBig", "structbolt_1_1mgt_1_1_task_too_big.html", null ],
    [ "TextureImagePointer", "classbolt_1_1mgt_1_1_texture_image_pointer.html", "classbolt_1_1mgt_1_1_texture_image_pointer" ]
];