var namespacebolt =
[
    [ "device", "namespacebolt_1_1device.html", "namespacebolt_1_1device" ],
    [ "mgt", "namespacebolt_1_1mgt.html", "namespacebolt_1_1mgt" ],
    [ "AbsFunctor", "structbolt_1_1_abs_functor.html", "structbolt_1_1_abs_functor" ],
    [ "AbsFunctorInplace", "structbolt_1_1_abs_functor_inplace.html", "structbolt_1_1_abs_functor_inplace" ],
    [ "AddValueFunctor", "structbolt_1_1_add_value_functor.html", "structbolt_1_1_add_value_functor" ],
    [ "AreCompatibleViews", "structbolt_1_1_are_compatible_views.html", null ],
    [ "BinaryFunctorImageView", "classbolt_1_1_binary_functor_image_view.html", "classbolt_1_1_binary_functor_image_view" ],
    [ "BinaryOperatorImageViewBase", "classbolt_1_1_binary_operator_image_view_base.html", "classbolt_1_1_binary_operator_image_view_base" ],
    [ "BoltError", "structbolt_1_1_bolt_error.html", null ],
    [ "BorderedSubImageView", "classbolt_1_1_bordered_sub_image_view.html", "classbolt_1_1_bordered_sub_image_view" ],
    [ "BorderHandlingTraits", "structbolt_1_1_border_handling_traits.html", null ],
    [ "BorderHandlingTraits< BorderHandling::kMirror >", "structbolt_1_1_border_handling_traits_3_01_border_handling_1_1k_mirror_01_4.html", null ],
    [ "BorderHandlingTraits< BorderHandling::kRepeat >", "structbolt_1_1_border_handling_traits_3_01_border_handling_1_1k_repeat_01_4.html", null ],
    [ "BorderHandlingTraits< BorderHandling::kZero >", "structbolt_1_1_border_handling_traits_3_01_border_handling_1_1k_zero_01_4.html", null ],
    [ "Byte", "structbolt_1_1_byte.html", null ],
    [ "CastFunctor", "structbolt_1_1_cast_functor.html", "structbolt_1_1_cast_functor" ],
    [ "Category", "structbolt_1_1_category.html", "structbolt_1_1_category" ],
    [ "CatmullRomWeights", "structbolt_1_1_catmull_rom_weights.html", null ],
    [ "CheckerBoardImageView", "classbolt_1_1_checker_board_image_view.html", "classbolt_1_1_checker_board_image_view" ],
    [ "CheckFloatIsFinite", "structbolt_1_1_check_float_is_finite.html", "structbolt_1_1_check_float_is_finite" ],
    [ "ClampFunctor", "structbolt_1_1_clamp_functor.html", "structbolt_1_1_clamp_functor" ],
    [ "ColumnAccessor", "classbolt_1_1_column_accessor.html", "classbolt_1_1_column_accessor" ],
    [ "CompileTimeFoldAnd", "structbolt_1_1_compile_time_fold_and.html", null ],
    [ "CompileTimeFoldAnd< tValue >", "structbolt_1_1_compile_time_fold_and_3_01t_value_01_4.html", null ],
    [ "ConjugateFunctor", "structbolt_1_1_conjugate_functor.html", "structbolt_1_1_conjugate_functor" ],
    [ "ConstantImageView", "classbolt_1_1_constant_image_view.html", "classbolt_1_1_constant_image_view" ],
    [ "ConstKernel", "classbolt_1_1_const_kernel.html", "classbolt_1_1_const_kernel" ],
    [ "ConstSpectrumBorderHandling", "structbolt_1_1_const_spectrum_border_handling.html", null ],
    [ "ConstSpectrumView", "classbolt_1_1_const_spectrum_view.html", "classbolt_1_1_const_spectrum_view" ],
    [ "ContiguousMemoryNeeded", "structbolt_1_1_contiguous_memory_needed.html", null ],
    [ "ConvolutionFunctor", "structbolt_1_1_convolution_functor.html", "structbolt_1_1_convolution_functor" ],
    [ "CopyDirection", "structbolt_1_1_copy_direction.html", null ],
    [ "CopyDirection< false, tFromIsHostView, true, true >", "structbolt_1_1_copy_direction_3_01false_00_01t_from_is_host_view_00_01true_00_01true_01_4.html", "structbolt_1_1_copy_direction_3_01false_00_01t_from_is_host_view_00_01true_00_01true_01_4" ],
    [ "CopyDirection< tFromIsDeviceView, tFromIsHostView, false, true >", "structbolt_1_1_copy_direction_3_01t_from_is_device_view_00_01t_from_is_host_view_00_01false_00_01true_01_4.html", "structbolt_1_1_copy_direction_3_01t_from_is_device_view_00_01t_from_is_host_view_00_01false_00_01true_01_4" ],
    [ "CopyDirection< tFromIsDeviceView, tFromIsHostView, true, false >", "structbolt_1_1_copy_direction_3_01t_from_is_device_view_00_01t_from_is_host_view_00_01true_00_01false_01_4.html", "structbolt_1_1_copy_direction_3_01t_from_is_device_view_00_01t_from_is_host_view_00_01true_00_01false_01_4" ],
    [ "CopyDirection< true, tFromIsHostView, true, true >", "structbolt_1_1_copy_direction_3_01true_00_01t_from_is_host_view_00_01true_00_01true_01_4.html", "structbolt_1_1_copy_direction_3_01true_00_01t_from_is_host_view_00_01true_00_01true_01_4" ],
    [ "CopyDirectionTag", "structbolt_1_1_copy_direction_tag.html", null ],
    [ "CopyHostToDeviceAsync", "structbolt_1_1_copy_host_to_device_async.html", null ],
    [ "CopyHostToDeviceAsync< TFromView, TElement, 1, TCudaType >", "structbolt_1_1_copy_host_to_device_async_3_01_t_from_view_00_01_t_element_00_011_00_01_t_cuda_type_01_4.html", null ],
    [ "CopyHostToHostHelper", "structbolt_1_1_copy_host_to_host_helper.html", null ],
    [ "CopyHostToHostHelper< 1, true >", "structbolt_1_1_copy_host_to_host_helper_3_011_00_01true_01_4.html", null ],
    [ "CopyHostToHostHelper< 2, true >", "structbolt_1_1_copy_host_to_host_helper_3_012_00_01true_01_4.html", null ],
    [ "CopyHostToHostHelper< 3, true >", "structbolt_1_1_copy_host_to_host_helper_3_013_00_01true_01_4.html", null ],
    [ "CopyHostToHostHelper< tDimension, false >", "structbolt_1_1_copy_host_to_host_helper_3_01t_dimension_00_01false_01_4.html", null ],
    [ "CubicInterpolator", "structbolt_1_1_cubic_interpolator.html", null ],
    [ "CubicInterpolatorImpl", "structbolt_1_1_cubic_interpolator_impl.html", null ],
    [ "CubicInterpolatorImpl< TBoundaryHandler, 1 >", "structbolt_1_1_cubic_interpolator_impl_3_01_t_boundary_handler_00_011_01_4.html", null ],
    [ "CudaError", "structbolt_1_1_cuda_error.html", null ],
    [ "CudaEvent", "classbolt_1_1_cuda_event.html", "classbolt_1_1_cuda_event" ],
    [ "CudaStream", "classbolt_1_1_cuda_stream.html", "classbolt_1_1_cuda_stream" ],
    [ "CudaType", "structbolt_1_1_cuda_type.html", null ],
    [ "CudaType< float >", "structbolt_1_1_cuda_type_3_01float_01_4.html", "structbolt_1_1_cuda_type_3_01float_01_4" ],
    [ "CudaType< Float2 >", "structbolt_1_1_cuda_type_3_01_float2_01_4.html", "structbolt_1_1_cuda_type_3_01_float2_01_4" ],
    [ "CudaType< Float4 >", "structbolt_1_1_cuda_type_3_01_float4_01_4.html", "structbolt_1_1_cuda_type_3_01_float4_01_4" ],
    [ "CudaType< int >", "structbolt_1_1_cuda_type_3_01int_01_4.html", "structbolt_1_1_cuda_type_3_01int_01_4" ],
    [ "CudaType< Int2 >", "structbolt_1_1_cuda_type_3_01_int2_01_4.html", "structbolt_1_1_cuda_type_3_01_int2_01_4" ],
    [ "CudaType< Int4 >", "structbolt_1_1_cuda_type_3_01_int4_01_4.html", "structbolt_1_1_cuda_type_3_01_int4_01_4" ],
    [ "CudaTypeDefaults", "structbolt_1_1_cuda_type_defaults.html", null ],
    [ "CuFFTError", "structbolt_1_1_cu_f_f_t_error.html", null ],
    [ "DataDimension", "structbolt_1_1_data_dimension.html", null ],
    [ "DataDimension< ImageStackAdapterView< TView > >", "structbolt_1_1_data_dimension_3_01_image_stack_adapter_view_3_01_t_view_01_4_01_4.html", null ],
    [ "DecreaseDimension", "structbolt_1_1_decrease_dimension.html", "structbolt_1_1_decrease_dimension" ],
    [ "DefaultForEachLocatorPolicy", "structbolt_1_1_default_for_each_locator_policy.html", "structbolt_1_1_default_for_each_locator_policy" ],
    [ "DefaultForEachPolicy", "structbolt_1_1_default_for_each_policy.html", null ],
    [ "DefaultTransformLocatorPolicy", "structbolt_1_1_default_transform_locator_policy.html", "structbolt_1_1_default_transform_locator_policy" ],
    [ "DefaultTransformPolicy", "structbolt_1_1_default_transform_policy.html", null ],
    [ "DefaultViewPolicy", "classbolt_1_1_default_view_policy.html", "classbolt_1_1_default_view_policy" ],
    [ "DeviceArrayConstView", "classbolt_1_1_device_array_const_view.html", "classbolt_1_1_device_array_const_view" ],
    [ "DeviceArrayView", "classbolt_1_1_device_array_view.html", "classbolt_1_1_device_array_view" ],
    [ "DeviceFftPlan", "structbolt_1_1_device_fft_plan.html", "structbolt_1_1_device_fft_plan" ],
    [ "DeviceFftPolicy", "classbolt_1_1_device_fft_policy.html", "classbolt_1_1_device_fft_policy" ],
    [ "DeviceFftPolicyHelper", "classbolt_1_1_device_fft_policy_helper.html", "classbolt_1_1_device_fft_policy_helper" ],
    [ "DeviceFuture", "classbolt_1_1_device_future.html", "classbolt_1_1_device_future" ],
    [ "DeviceFuture< void >", "classbolt_1_1_device_future_3_01void_01_4.html", "classbolt_1_1_device_future_3_01void_01_4" ],
    [ "DeviceImage", "classbolt_1_1_device_image.html", "classbolt_1_1_device_image" ],
    [ "DeviceImageConstView", "classbolt_1_1_device_image_const_view.html", "classbolt_1_1_device_image_const_view" ],
    [ "DeviceImageView", "classbolt_1_1_device_image_view.html", "classbolt_1_1_device_image_view" ],
    [ "DeviceImageViewBase", "classbolt_1_1_device_image_view_base.html", "classbolt_1_1_device_image_view_base" ],
    [ "DeviceMemoryInfo", "structbolt_1_1_device_memory_info.html", "structbolt_1_1_device_memory_info" ],
    [ "DeviceProperties", "structbolt_1_1_device_properties.html", "structbolt_1_1_device_properties" ],
    [ "DimensionValue", "structbolt_1_1_dimension_value.html", null ],
    [ "DivisionImageView", "classbolt_1_1_division_image_view.html", "classbolt_1_1_division_image_view" ],
    [ "DynamicDeviceKernel", "structbolt_1_1_dynamic_device_kernel.html", "structbolt_1_1_dynamic_device_kernel" ],
    [ "DynamicHostKernel", "structbolt_1_1_dynamic_host_kernel.html", "structbolt_1_1_dynamic_host_kernel" ],
    [ "DynamicKernelBase", "classbolt_1_1_dynamic_kernel_base.html", "classbolt_1_1_dynamic_kernel_base" ],
    [ "ElementPositionPair", "structbolt_1_1_element_position_pair.html", "structbolt_1_1_element_position_pair" ],
    [ "ElementPositionView", "classbolt_1_1_element_position_view.html", "classbolt_1_1_element_position_view" ],
    [ "EmbeddingFromStridesAndSizesHelper", "structbolt_1_1_embedding_from_strides_and_sizes_helper.html", null ],
    [ "EmbeddingFromStridesAndSizesHelper< Stack<-1, -1 > >", "structbolt_1_1_embedding_from_strides_and_sizes_helper_3_01_stack_3-1_00_01-1_01_4_01_4.html", null ],
    [ "ExceptionBase", "classbolt_1_1_exception_base.html", "classbolt_1_1_exception_base" ],
    [ "ExecutionPolicy", "structbolt_1_1_execution_policy.html", "structbolt_1_1_execution_policy" ],
    [ "FFTAmplitudeFunctor", "structbolt_1_1_f_f_t_amplitude_functor.html", "structbolt_1_1_f_f_t_amplitude_functor" ],
    [ "FftCalculator", "classbolt_1_1_fft_calculator.html", "classbolt_1_1_fft_calculator" ],
    [ "FFTWError", "structbolt_1_1_f_f_t_w_error.html", null ],
    [ "FileInfoTag", "structbolt_1_1_file_info_tag.html", null ],
    [ "FillTag", "structbolt_1_1_fill_tag.html", null ],
    [ "Forward", "structbolt_1_1_forward.html", null ],
    [ "GenerateIntSequence", "structbolt_1_1_generate_int_sequence.html", "structbolt_1_1_generate_int_sequence" ],
    [ "GetPositionInIntSequence", "structbolt_1_1_get_position_in_int_sequence.html", "structbolt_1_1_get_position_in_int_sequence" ],
    [ "GilAdaptorImage", "classbolt_1_1_gil_adaptor_image.html", "classbolt_1_1_gil_adaptor_image" ],
    [ "GilViewTraits", "structbolt_1_1_gil_view_traits.html", "structbolt_1_1_gil_view_traits" ],
    [ "GilViewTypeFromImageViewType", "structbolt_1_1_gil_view_type_from_image_view_type.html", "structbolt_1_1_gil_view_type_from_image_view_type" ],
    [ "HadamardFunctor", "structbolt_1_1_hadamard_functor.html", "structbolt_1_1_hadamard_functor" ],
    [ "HalfSpectrumView", "classbolt_1_1_half_spectrum_view.html", "classbolt_1_1_half_spectrum_view" ],
    [ "HostArrayConstView", "classbolt_1_1_host_array_const_view.html", "classbolt_1_1_host_array_const_view" ],
    [ "HostArrayView", "classbolt_1_1_host_array_view.html", "classbolt_1_1_host_array_view" ],
    [ "HostComplexType", "unionbolt_1_1_host_complex_type.html", "unionbolt_1_1_host_complex_type" ],
    [ "HostFftPlan", "structbolt_1_1_host_fft_plan.html", "structbolt_1_1_host_fft_plan" ],
    [ "HostFftPolicy", "classbolt_1_1_host_fft_policy.html", "classbolt_1_1_host_fft_policy" ],
    [ "HostFftPolicyHelper", "classbolt_1_1_host_fft_policy_helper.html", "classbolt_1_1_host_fft_policy_helper" ],
    [ "HostImage", "classbolt_1_1_host_image.html", "classbolt_1_1_host_image" ],
    [ "HostImageConstView", "classbolt_1_1_host_image_const_view.html", "classbolt_1_1_host_image_const_view" ],
    [ "HostImageView", "classbolt_1_1_host_image_view.html", "classbolt_1_1_host_image_view" ],
    [ "HostImageViewBase", "classbolt_1_1_host_image_view_base.html", "classbolt_1_1_host_image_view_base" ],
    [ "HybridImageViewBase", "classbolt_1_1_hybrid_image_view_base.html", "classbolt_1_1_hybrid_image_view_base" ],
    [ "IdentityFunctor", "structbolt_1_1_identity_functor.html", "structbolt_1_1_identity_functor" ],
    [ "ImageLocator", "classbolt_1_1_image_locator.html", "classbolt_1_1_image_locator" ],
    [ "ImageStackAdapter", "classbolt_1_1_image_stack_adapter.html", "classbolt_1_1_image_stack_adapter" ],
    [ "ImageStackAdapterView", "classbolt_1_1_image_stack_adapter_view.html", "classbolt_1_1_image_stack_adapter_view" ],
    [ "IncompatibleViewSizes", "structbolt_1_1_incompatible_view_sizes.html", null ],
    [ "IncrementFunctor", "structbolt_1_1_increment_functor.html", "structbolt_1_1_increment_functor" ],
    [ "Index", "structbolt_1_1_index.html", "structbolt_1_1_index" ],
    [ "Index< 0, THead, TTail... >", "structbolt_1_1_index_3_010_00_01_t_head_00_01_t_tail_8_8_8_01_4.html", "structbolt_1_1_index_3_010_00_01_t_head_00_01_t_tail_8_8_8_01_4" ],
    [ "Index< tIndex, THead, TTail... >", "structbolt_1_1_index_3_01t_index_00_01_t_head_00_01_t_tail_8_8_8_01_4.html", null ],
    [ "IndexView", "classbolt_1_1_index_view.html", "classbolt_1_1_index_view" ],
    [ "InterpolatedView", "classbolt_1_1_interpolated_view.html", "classbolt_1_1_interpolated_view" ],
    [ "IntSequence", "classbolt_1_1_int_sequence.html", null ],
    [ "InvalidNDRange", "structbolt_1_1_invalid_n_d_range.html", null ],
    [ "Inverse", "structbolt_1_1_inverse.html", null ],
    [ "IsArrayView", "structbolt_1_1_is_array_view.html", null ],
    [ "IsArrayView< DeviceArrayConstView< TElement > >", "structbolt_1_1_is_array_view_3_01_device_array_const_view_3_01_t_element_01_4_01_4.html", null ],
    [ "IsArrayView< DeviceArrayView< TElement > >", "structbolt_1_1_is_array_view_3_01_device_array_view_3_01_t_element_01_4_01_4.html", null ],
    [ "IsArrayView< HostArrayConstView< TElement > >", "structbolt_1_1_is_array_view_3_01_host_array_const_view_3_01_t_element_01_4_01_4.html", null ],
    [ "IsArrayView< HostArrayView< TElement > >", "structbolt_1_1_is_array_view_3_01_host_array_view_3_01_t_element_01_4_01_4.html", null ],
    [ "IsDeviceImageView", "structbolt_1_1_is_device_image_view.html", "structbolt_1_1_is_device_image_view" ],
    [ "IsDevicePolicy", "structbolt_1_1_is_device_policy.html", null ],
    [ "IsDevicePolicy< DeviceFftPolicy< TDirection, TStackPolicy > >", "structbolt_1_1_is_device_policy_3_01_device_fft_policy_3_01_t_direction_00_01_t_stack_policy_01_4_01_4.html", null ],
    [ "IsDeviceView", "structbolt_1_1_is_device_view.html", null ],
    [ "IsHostImageView", "structbolt_1_1_is_host_image_view.html", "structbolt_1_1_is_host_image_view" ],
    [ "IsHostView", "structbolt_1_1_is_host_view.html", null ],
    [ "IsImageView", "structbolt_1_1_is_image_view.html", null ],
    [ "IsImageView< ImageStackAdapterView< TImageView > >", "structbolt_1_1_is_image_view_3_01_image_stack_adapter_view_3_01_t_image_view_01_4_01_4.html", null ],
    [ "IsImageViewPair", "structbolt_1_1_is_image_view_pair.html", null ],
    [ "IsInterpolatedView", "structbolt_1_1_is_interpolated_view.html", null ],
    [ "IsInterpolatedView< InterpolatedView< TView, TInterpolator > >", "structbolt_1_1_is_interpolated_view_3_01_interpolated_view_3_01_t_view_00_01_t_interpolator_01_4_01_4.html", null ],
    [ "IsInterpolatedView< TextureImageView< TElement, tDimension, TCudaType > >", "structbolt_1_1_is_interpolated_view_3_01_texture_image_view_3_01_t_element_00_01t_dimension_00_01_t_cuda_type_01_4_01_4.html", null ],
    [ "IsMemcpyAble", "structbolt_1_1_is_memcpy_able.html", null ],
    [ "IsMemcpyAble< ConstSpectrumView< TView > >", "structbolt_1_1_is_memcpy_able_3_01_const_spectrum_view_3_01_t_view_01_4_01_4.html", null ],
    [ "IsMemcpyAble< HalfSpectrumView< TView > >", "structbolt_1_1_is_memcpy_able_3_01_half_spectrum_view_3_01_t_view_01_4_01_4.html", null ],
    [ "IsMemoryBasedView", "structbolt_1_1_is_memory_based_view.html", null ],
    [ "IsTextureView", "structbolt_1_1_is_texture_view.html", null ],
    [ "IsTextureView< TextureImageConstView< TElement, tDimension, TCudaType > >", "structbolt_1_1_is_texture_view_3_01_texture_image_const_view_3_01_t_element_00_01t_dimension_00_01_t_cuda_type_01_4_01_4.html", null ],
    [ "IsTextureView< TextureImageView< TElement, tDimension, TCudaType > >", "structbolt_1_1_is_texture_view_3_01_texture_image_view_3_01_t_element_00_01t_dimension_00_01_t_cuda_type_01_4_01_4.html", null ],
    [ "IsValueInIntSequence", "structbolt_1_1_is_value_in_int_sequence.html", "structbolt_1_1_is_value_in_int_sequence" ],
    [ "IsVector", "structbolt_1_1_is_vector.html", null ],
    [ "KernelView", "structbolt_1_1_kernel_view.html", "structbolt_1_1_kernel_view" ],
    [ "KernelView< TConvolutionKernel, false >", "structbolt_1_1_kernel_view_3_01_t_convolution_kernel_00_01false_01_4.html", "structbolt_1_1_kernel_view_3_01_t_convolution_kernel_00_01false_01_4" ],
    [ "LinearCombinationImageView", "classbolt_1_1_linear_combination_image_view.html", "classbolt_1_1_linear_combination_image_view" ],
    [ "LinearInterpolator", "structbolt_1_1_linear_interpolator.html", null ],
    [ "LinearInterpolatorImpl", "structbolt_1_1_linear_interpolator_impl.html", null ],
    [ "LinearInterpolatorImpl< TBoundaryHandler, 1 >", "structbolt_1_1_linear_interpolator_impl_3_01_t_boundary_handler_00_011_01_4.html", null ],
    [ "LineInfoTag", "structbolt_1_1_line_info_tag.html", null ],
    [ "LocatorConstruction", "structbolt_1_1_locator_construction.html", null ],
    [ "LongIndexViewPolicy", "classbolt_1_1_long_index_view_policy.html", "classbolt_1_1_long_index_view_policy" ],
    [ "LowerLimitFunctor", "structbolt_1_1_lower_limit_functor.html", "structbolt_1_1_lower_limit_functor" ],
    [ "MagnitudeFunctor", "structbolt_1_1_magnitude_functor.html", "structbolt_1_1_magnitude_functor" ],
    [ "Matrix", "classbolt_1_1_matrix.html", "classbolt_1_1_matrix" ],
    [ "MatrixTraits", "structbolt_1_1_matrix_traits.html", null ],
    [ "MatrixTraits< Matrix< TType, tRowCount, tColCount > >", "structbolt_1_1_matrix_traits_3_01_matrix_3_01_t_type_00_01t_row_count_00_01t_col_count_01_4_01_4.html", "structbolt_1_1_matrix_traits_3_01_matrix_3_01_t_type_00_01t_row_count_00_01t_col_count_01_4_01_4" ],
    [ "MaxFunctor", "structbolt_1_1_max_functor.html", "structbolt_1_1_max_functor" ],
    [ "MaxRangeConverter", "classbolt_1_1_max_range_converter.html", "classbolt_1_1_max_range_converter" ],
    [ "MaxWithLimitFunctor", "structbolt_1_1_max_with_limit_functor.html", "structbolt_1_1_max_with_limit_functor" ],
    [ "MemoryUnit", "structbolt_1_1_memory_unit.html", null ],
    [ "MeshGridView", "classbolt_1_1_mesh_grid_view.html", "classbolt_1_1_mesh_grid_view" ],
    [ "MinMaxFunctor", "structbolt_1_1_min_max_functor.html", "structbolt_1_1_min_max_functor" ],
    [ "MinMaxMeanFunctor", "structbolt_1_1_min_max_mean_functor.html", "structbolt_1_1_min_max_mean_functor" ],
    [ "MinWithLimitFunctor", "structbolt_1_1_min_with_limit_functor.html", "structbolt_1_1_min_with_limit_functor" ],
    [ "MirrorImageView", "classbolt_1_1_mirror_image_view.html", "classbolt_1_1_mirror_image_view" ],
    [ "MovedFromFlag", "structbolt_1_1_moved_from_flag.html", "structbolt_1_1_moved_from_flag" ],
    [ "MultiplicationImageView", "classbolt_1_1_multiplication_image_view.html", "classbolt_1_1_multiplication_image_view" ],
    [ "MultiplyByFactorFunctor", "structbolt_1_1_multiply_by_factor_functor.html", "structbolt_1_1_multiply_by_factor_functor" ],
    [ "MultiViewTraits", "structbolt_1_1_multi_view_traits.html", null ],
    [ "NAryOperatorImageView", "classbolt_1_1_n_ary_operator_image_view.html", "classbolt_1_1_n_ary_operator_image_view" ],
    [ "NearestNeighborInterpolator", "structbolt_1_1_nearest_neighbor_interpolator.html", null ],
    [ "NormalizeFunctor", "structbolt_1_1_normalize_functor.html", "structbolt_1_1_normalize_functor" ],
    [ "NotYetImplemented", "structbolt_1_1_not_yet_implemented.html", null ],
    [ "NumericTypeWrapper", "classbolt_1_1_numeric_type_wrapper.html", "classbolt_1_1_numeric_type_wrapper" ],
    [ "Ordinal", "structbolt_1_1_ordinal.html", null ],
    [ "Ordinal< T, F, R... >", "structbolt_1_1_ordinal_3_01_t_00_01_f_00_01_r_8_8_8_01_4.html", null ],
    [ "Ordinal< T, T, R... >", "structbolt_1_1_ordinal_3_01_t_00_01_t_00_01_r_8_8_8_01_4.html", null ],
    [ "PaddedImageView", "classbolt_1_1_padded_image_view.html", "classbolt_1_1_padded_image_view" ],
    [ "PerceptualScaleFunctor", "structbolt_1_1_perceptual_scale_functor.html", "structbolt_1_1_perceptual_scale_functor" ],
    [ "PhaseFunctor", "structbolt_1_1_phase_functor.html", "structbolt_1_1_phase_functor" ],
    [ "PhaseShiftFunctor", "structbolt_1_1_phase_shift_functor.html", "structbolt_1_1_phase_shift_functor" ],
    [ "PixelElementBaseTypeSelector", "structbolt_1_1_pixel_element_base_type_selector.html", "structbolt_1_1_pixel_element_base_type_selector" ],
    [ "PixelElementBaseTypeSelector< TGilViewPixelElementType, typename std::enable_if< std::is_floating_point< typename TGilViewPixelElementType::base_channel_t >::value >::type >", "structbolt_1_1_pixel_element_base_type_selector_3_01_t_gil_view_pixel_element_type_00_01typename815a07f40febe6440f10189b56170f5a.html", "structbolt_1_1_pixel_element_base_type_selector_3_01_t_gil_view_pixel_element_type_00_01typename815a07f40febe6440f10189b56170f5a" ],
    [ "Quaternion", "classbolt_1_1_quaternion.html", "classbolt_1_1_quaternion" ],
    [ "Reduce", "classbolt_1_1_reduce.html", "classbolt_1_1_reduce" ],
    [ "Reduce< TOutputValue, true >", "classbolt_1_1_reduce_3_01_t_output_value_00_01true_01_4.html", "classbolt_1_1_reduce_3_01_t_output_value_00_01true_01_4" ],
    [ "ReduceImplementation", "structbolt_1_1_reduce_implementation.html", null ],
    [ "Region", "structbolt_1_1_region.html", "structbolt_1_1_region" ],
    [ "RepeatVector", "classbolt_1_1_repeat_vector.html", "classbolt_1_1_repeat_vector" ],
    [ "RotatedAccessOperator", "structbolt_1_1_rotated_access_operator.html", "structbolt_1_1_rotated_access_operator" ],
    [ "RoundFunctor", "structbolt_1_1_round_functor.html", "structbolt_1_1_round_functor" ],
    [ "ScalingTransformation", "structbolt_1_1_scaling_transformation.html", "structbolt_1_1_scaling_transformation" ],
    [ "SharedMemoryStaticArray", "classbolt_1_1_shared_memory_static_array.html", "classbolt_1_1_shared_memory_static_array" ],
    [ "SinusImageView", "classbolt_1_1_sinus_image_view.html", "classbolt_1_1_sinus_image_view" ],
    [ "SizePair", "structbolt_1_1_size_pair.html", null ],
    [ "SliceImageView", "classbolt_1_1_slice_image_view.html", null ],
    [ "SliceImageView< TView, tSliceDimension, false >", "classbolt_1_1_slice_image_view_3_01_t_view_00_01t_slice_dimension_00_01false_01_4.html", "classbolt_1_1_slice_image_view_3_01_t_view_00_01t_slice_dimension_00_01false_01_4" ],
    [ "SliceImageView< TView, tSliceDimension, true >", "classbolt_1_1_slice_image_view_3_01_t_view_00_01t_slice_dimension_00_01true_01_4.html", "classbolt_1_1_slice_image_view_3_01_t_view_00_01t_slice_dimension_00_01true_01_4" ],
    [ "SliceOutOfRange", "structbolt_1_1_slice_out_of_range.html", null ],
    [ "SquareFunctor", "structbolt_1_1_square_functor.html", "structbolt_1_1_square_functor" ],
    [ "SquareRootFunctor", "structbolt_1_1_square_root_functor.html", "structbolt_1_1_square_root_functor" ],
    [ "Stack", "structbolt_1_1_stack.html", null ],
    [ "StackIndex", "structbolt_1_1_stack_index.html", "structbolt_1_1_stack_index" ],
    [ "StackSize", "structbolt_1_1_stack_size.html", "structbolt_1_1_stack_size" ],
    [ "Stride", "structbolt_1_1_stride.html", "structbolt_1_1_stride" ],
    [ "SubImageView", "classbolt_1_1_sub_image_view.html", "classbolt_1_1_sub_image_view" ],
    [ "TextureImage", "classbolt_1_1_texture_image.html", "classbolt_1_1_texture_image" ],
    [ "TextureImageConstView", "classbolt_1_1_texture_image_const_view.html", "classbolt_1_1_texture_image_const_view" ],
    [ "TextureImageView", "classbolt_1_1_texture_image_view.html", "classbolt_1_1_texture_image_view" ],
    [ "TransformedImageView", "classbolt_1_1_transformed_image_view.html", "classbolt_1_1_transformed_image_view" ],
    [ "Tuple", "structbolt_1_1_tuple.html", "structbolt_1_1_tuple" ],
    [ "UnaryOperatorImageView", "classbolt_1_1_unary_operator_image_view.html", "classbolt_1_1_unary_operator_image_view" ],
    [ "UnaryOperatorWithMetadataImageView", "classbolt_1_1_unary_operator_with_metadata_image_view.html", "classbolt_1_1_unary_operator_with_metadata_image_view" ],
    [ "UnifiedImage", "classbolt_1_1_unified_image.html", "classbolt_1_1_unified_image" ],
    [ "UnifiedImageConstView", "classbolt_1_1_unified_image_const_view.html", "classbolt_1_1_unified_image_const_view" ],
    [ "UnifiedImageView", "classbolt_1_1_unified_image_view.html", "classbolt_1_1_unified_image_view" ],
    [ "UniqueIdImageView", "classbolt_1_1_unique_id_image_view.html", "classbolt_1_1_unique_id_image_view" ],
    [ "UpperLimitFunctor", "structbolt_1_1_upper_limit_functor.html", "structbolt_1_1_upper_limit_functor" ],
    [ "Vector", "classbolt_1_1_vector.html", "classbolt_1_1_vector" ],
    [ "VectorTraits", "structbolt_1_1_vector_traits.html", null ],
    [ "VectorTraits< RepeatVector< TType > >", "structbolt_1_1_vector_traits_3_01_repeat_vector_3_01_t_type_01_4_01_4.html", "structbolt_1_1_vector_traits_3_01_repeat_vector_3_01_t_type_01_4_01_4" ],
    [ "VectorTraits< Vector< TType, tDim > >", "structbolt_1_1_vector_traits_3_01_vector_3_01_t_type_00_01t_dim_01_4_01_4.html", "structbolt_1_1_vector_traits_3_01_vector_3_01_t_type_00_01t_dim_01_4_01_4" ],
    [ "ViewCategory", "structbolt_1_1_view_category.html", null ],
    [ "ViewIterator", "structbolt_1_1_view_iterator.html", "structbolt_1_1_view_iterator" ],
    [ "ZipValues", "structbolt_1_1_zip_values.html", "structbolt_1_1_zip_values" ]
];